배포

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -41,33 +41,33 @@ jobs:
       - name: Set up Docker Buildx  ----도커 셋업----
         uses: docker/setup-buildx-action@v2
 
-        #통합테스트
+      #   #통합테스트
 
-      - name: Install Docker Compose ----도커 컴포즈설치-----
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y docker-compose
+      # - name: Install Docker Compose ----도커 컴포즈설치-----
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y docker-compose
 
-      - name: Run mysql ----통합테스트를 위한 mysql컨테이너 RUN---
-        run: |
-           docker compose -f ./docker-compose-it-test.yml up -d mysql
+      # - name: Run mysql ----통합테스트를 위한 mysql컨테이너 RUN---
+      #   run: |
+      #      docker compose -f ./docker-compose-it-test.yml up -d mysql
 
-      - name: Run Redis ----통합테스트를 위한 redis컨테이너 RUN---
-        run: |
-           docker compose -f ./docker-compose-it-test.yml up -d redis-master-1    
+      # - name: Run Redis ----통합테스트를 위한 redis컨테이너 RUN---
+      #   run: |
+      #      docker compose -f ./docker-compose-it-test.yml up -d redis-master-1    
 
-      - name: Wait for DB ----통합테스트 대기중....---
-        run: |
-          sleep 10  # 적절한 대기 시간 설정
+      # - name: Wait for DB ----통합테스트 대기중....---
+      #   run: |
+      #     sleep 10  # 적절한 대기 시간 설정
 
-      - name: Run IT Tests  ----통합테스트---
-        run: |
-          docker-compose -f ./docker-compose-it-test.yml up --abort-on-container-exit backend_match1    # 컨테이너 빌드 및 실행
-          # 테스트가 실패한 경우에 워크플로우를 실패로 처리
-          if [ $? -ne 0 ]; then
-          echo "IT tests failed, stopping workflow."
-          exit 1
-          fi          
+      # - name: Run IT Tests  ----통합테스트---
+      #   run: |
+      #     docker-compose -f ./docker-compose-it-test.yml up --abort-on-container-exit backend_match1    # 컨테이너 빌드 및 실행
+      #     # 테스트가 실패한 경우에 워크플로우를 실패로 처리
+      #     if [ $? -ne 0 ]; then
+      #     echo "IT tests failed, stopping workflow."
+      #     exit 1
+      #     fi          
 
       - name: Login Docker  ----도커로그인----
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
@@ -90,6 +90,18 @@ jobs:
         run: |
           docker build -f ./frontend/Dockerfile-deploy -t kimyong120413/randchatfrontend:$TAG_NAME .
           docker push kimyong120413/randchatfrontend:$TAG_NAME
+ 
+
+      - name: BACKEND-CHAT-WS Image Build  ----채팅 웹소켓 서버 이미지빌드---
+        run: |
+          docker build -f ./backend/Dockerfile-chat-deploy -t kimyong120413/randchatbackendchatws:$TAG_NAME .
+          docker push kimyong120413/randchatbackendchatws:$TAG_NAME
+
+       - name: BACKEND-CHAT-IO Image Build  ----채팅 I/O 서버 이미지빌드---
+        run: |
+          docker build -f ./backend/Dockerfile-chat-API-deploy -t kimyong120413/randchatbackendchatio:$TAG_NAME .
+          docker push kimyong120413/randchatbackendchatio:$TAG_NAME         
+
  
       # - name: NGINX IMAGE BUILD ----엔진엑스 서버 이미지빌드---
       #   run: |
